# Generated by Django 2.1.7 on 2019-03-31 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=250)),
                ('documento', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=250)),
            ],
        ),
    ]
