# Generated by Django 2.1.7 on 2019-03-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emitente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emitente',
            options={'ordering': ('-criado_em',)},
        ),
    ]
