version: '3'

services:
    db:
        image: postgres:9.6
        volumes:
            - data:/var/lib/postgresql/data
    api:
        build: .
        ports:
            - 8000:8000
        depends_on:
            - db

volumes:
    data:
