version: '3'

services:
    db:
        image: postgres:9.6
        volumes:
            - data:/var/lib/postgresql/data
    api:
        image: flaviogf/emissor_de_promissoria:latest
        ports:
            - 80:8000
        environment:
            - DJANGO_SETTINGS_MODULE=api.settings_prod
            - URL_RABBIT=rabbit
        command: |
            pipenv run gunicorn api.wsgi -b 0.0.0.0
        depends_on:
          - rabbit
          - db
    email:
        image: flaviogf/emissor_de_promissoria_email:latest
        environment:
            - URL_RABBIT=rabbit
        command: |
            pipenv run python -u app.py
        depends_on:
          - rabbit
    rabbit:
        image: rabbitmq:3


volumes:
    data:
