# Generated by Django 2.1.7 on 2019-03-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emitentes', '0002_auto_20190326_0159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmitenteData',
            new_name='EmitenteModel',
        ),
    ]
