# Generated by Django 2.1.7 on 2019-03-19 11:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contatos', '0001_initial'),
        ('contas', '0004_auto_20190318_1129'),
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promisoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contas', models.ManyToManyField(to='contas.Conta')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enderecos.Endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
