# Generated by Django 2.1.7 on 2019-03-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190320_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promisoria',
            old_name='data_baixa',
            new_name='data_recebimento',
        ),
        migrations.RenameField(
            model_name='promisoria',
            old_name='baixada',
            new_name='recebida',
        ),
    ]
