# Generated by Django 2.1.7 on 2019-03-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190321_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promisoria',
            options={'ordering': ('-criado_em',)},
        ),
    ]
