# Generated by Django 2.1.7 on 2019-03-28 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiariomodel',
            options={'ordering': ('criado_em',)},
        ),
    ]
