# Generated by Django 2.1.7 on 2019-02-20 13:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contatos', '0008_auto_20190220_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('conta_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_recebimento_esperado', models.DateField()),
                ('data_recebimento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='contatos.Contato')),
            ],
        ),
    ]
