# Generated by Django 2.1.7 on 2019-03-15 12:25

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_recebimento', models.DateField(default=datetime.date.today)),
                ('recebida', models.BooleanField(default=False)),
            ],
        ),
    ]
