# Generated by Django 2.1.7 on 2019-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
