# Generated by Django 2.1.7 on 2019-03-18 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20190318_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='atualizado_em',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 11, 28, 54, 364791, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='conta',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 11, 28, 54, 364756, tzinfo=utc)),
        ),
    ]
