# Generated by Django 2.1.7 on 2019-03-01 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20190220_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_recebimento_esperado', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='conta',
            options={'ordering': ['data_recebimento_esperado']},
        ),
        migrations.AddField(
            model_name='historicoconta',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='contas.Conta'),
        ),
    ]
