# Generated by Django 2.1.7 on 2019-03-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20190318_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
