# Generated by Django 2.1.7 on 2019-03-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20190301_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoconta',
            options={'ordering': ['-atualizado_em']},
        ),
    ]
