# Generated by Django 2.1.7 on 2019-03-31 19:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emitentes', '0001_initial'),
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promissoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=250)),
                ('data_vencimento', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('recebida', models.BooleanField(default=False)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiarios.Beneficiario')),
                ('emitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emitentes.Emitente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
