# Generated by Django 2.1.7 on 2019-03-15 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=9)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
    ]
