# Generated by Django 2.1.7 on 2019-03-14 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_auto_20190314_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='atualizado_em',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 15, 7, 0, 388905)),
        ),
        migrations.AddField(
            model_name='endereco',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 15, 7, 0, 388882)),
        ),
    ]
