# Generated by Django 2.1.7 on 2019-02-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='endereco', serialize=False, to='contatos.Contato')),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
            ],
        ),
    ]
