# Generated by Django 2.1.7 on 2019-02-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
    ]
