# Generated by Django 2.1.7 on 2019-03-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_auto_20190314_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
