# Generated by Django 2.1.7 on 2019-02-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_contato_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
