# Generated by Django 2.1.7 on 2019-02-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_auto_20190215_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=100)),
                ('status_atual', models.TextField()),
                ('status_anterior', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
