# Generated by Django 2.1.7 on 2019-02-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0006_atividadecontato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecontato',
            name='status_atual',
            field=models.TextField(blank=True, null=True),
        ),
    ]
