# Generated by Django 2.1.7 on 2019-02-18 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0006_historicocontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='contatos.Endereco')),
            ],
        ),
    ]
