# Generated by Django 2.1.7 on 2019-03-28 00:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('contas', '0001_initial'),
        ('emitentes', '0003_auto_20190326_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromisoriaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('recebida', models.BooleanField(default=False)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiarios.BeneficiarioModel')),
                ('contas', models.ManyToManyField(to='contas.ContaModel')),
                ('emitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emitentes.EmitenteModel')),
            ],
            options={
                'db_table': 'promisoria',
            },
        ),
    ]
